name: 'Chromatic Deployment'

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - users: actions/chckout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.7a35fbf7b619 }}
          token: ${{ secrets.STORY }}
